/// Double-submit cookie CSRF protection keyed on PATCHWATCH_CSRF_SECRET.
///
/// Workflow:
///   GET  -> if no csrf_token cookie, generate one and add Set-Cookie to response
///   POST -> require X-CSRF-Token header == csrf_token cookie value; 403 otherwise
///
/// Token format: {nonce_hex}.{hmac_sha256_hex}
/// The HMAC verifies the token was generated by this server (sub-domain injection defense).
use axum::{
    body::Body,
    http::{Request, Response, StatusCode, header},
    middleware::Next,
};
use hmac::{Hmac, KeyInit, Mac};
use sha2::Sha256;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

type HmacSha256 = Hmac<Sha256>;

static COUNTER: AtomicU64 = AtomicU64::new(0);

fn nonce_bytes() -> [u8; 32] {
    let t = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos() as u64;
    let c = COUNTER.fetch_add(1, Ordering::Relaxed);
    // Mix time + counter through sha256 for a non-repeating nonce.
    // Not cryptographically secure randomness, but acceptable for a localhost-only tool.
    use sha2::Digest;
    let mut h = sha2::Sha256::new();
    h.update(t.to_le_bytes());
    h.update(c.to_le_bytes());
    h.update(b"patchwatch-csrf-nonce");
    h.finalize().into()
}

/// Public for integration tests that need a valid token to call POST endpoints.
pub fn generate_token_for_test(secret: &str) -> String {
    make_token(secret.as_bytes())
}

fn make_token(secret: &[u8]) -> String {
    let nonce = nonce_bytes();
    let nonce_hex = hex::encode(nonce);
    let mut mac = HmacSha256::new_from_slice(secret).expect("HMAC accepts any key length");
    mac.update(&nonce);
    let token_hex = hex::encode(mac.finalize().into_bytes());
    format!("{}.{}", nonce_hex, token_hex)
}

fn verify_token(secret: &[u8], cookie_value: &str) -> bool {
    let mut parts = cookie_value.splitn(2, '.');
    let (nonce_hex, token_hex) = match (parts.next(), parts.next()) {
        (Some(n), Some(t)) => (n, t),
        _ => return false,
    };
    let nonce = match hex::decode(nonce_hex) {
        Ok(b) => b,
        Err(_) => return false,
    };
    let expected = match hex::decode(token_hex) {
        Ok(b) => b,
        Err(_) => return false,
    };
    let mut mac = match HmacSha256::new_from_slice(secret) {
        Ok(m) => m,
        Err(_) => return false,
    };
    mac.update(&nonce);
    mac.verify_slice(&expected).is_ok()
}

fn get_cookie(req: &Request<Body>, name: &str) -> Option<String> {
    let header_val = req.headers().get(header::COOKIE)?.to_str().ok()?;
    for cookie in header_val.split(';') {
        let cookie = cookie.trim();
        if let Some(value) = cookie.strip_prefix(&format!("{}=", name)) {
            return Some(value.to_owned());
        }
    }
    None
}

pub async fn csrf_middleware(
    secret: String,
    mut req: Request<Body>,
    next: Next,
) -> Result<Response<Body>, StatusCode> {
    let is_safe = matches!(req.method().as_str(), "GET" | "HEAD" | "OPTIONS" | "TRACE");
    let existing_token = get_cookie(&req, "csrf_token");

    if !is_safe {
        // Enforce CSRF check on mutating requests.
        let cookie_token = match &existing_token {
            Some(t) => t.as_str(),
            None => return Err(StatusCode::FORBIDDEN),
        };

        // Check X-CSRF-Token header (used by HTMX and JS).
        let header_token = req
            .headers()
            .get("x-csrf-token")
            .and_then(|v| v.to_str().ok());

        let submitted = match header_token {
            Some(t) => t,
            None => return Err(StatusCode::FORBIDDEN),
        };

        if submitted != cookie_token {
            return Err(StatusCode::FORBIDDEN);
        }

        // Verify the cookie itself was issued by us (prevents sub-domain cookie injection).
        if !verify_token(secret.as_bytes(), cookie_token) {
            return Err(StatusCode::FORBIDDEN);
        }
    }

    // On safe requests with no existing cookie, mint a token now and inject it into
    // the request so the handler renders the same value it will receive on the next
    // request. Without this, the first page load would render an empty CSRF token
    // into the HTML while the response sets a fresh cookie, causing every subsequent
    // POST from that page to fail with 403 until the user refreshed.
    let token = if is_safe {
        Some(existing_token.clone().unwrap_or_else(|| {
            let new_token = make_token(secret.as_bytes());
            inject_cookie(&mut req, "csrf_token", &new_token);
            new_token
        }))
    } else {
        None
    };

    let mut response = next.run(req).await;

    if let Some(token) = token {
        let cookie = format!(
            "csrf_token={}; Path=/; SameSite=Strict; HttpOnly",
            token
        );
        if let Ok(val) = cookie.parse() {
            response.headers_mut().append(header::SET_COOKIE, val);
        }
    }

    Ok(response)
}

fn inject_cookie(req: &mut Request<Body>, name: &str, value: &str) {
    let headers = req.headers_mut();
    let new_pair = format!("{}={}", name, value);
    let merged = match headers.get(header::COOKIE).and_then(|v| v.to_str().ok()) {
        Some(existing) if !existing.is_empty() => format!("{}; {}", existing, new_pair),
        _ => new_pair,
    };
    if let Ok(val) = merged.parse() {
        headers.insert(header::COOKIE, val);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn token_round_trips() {
        let secret = b"test-secret";
        let token = make_token(secret);
        assert!(verify_token(secret, &token), "token should verify");
        assert!(!verify_token(b"wrong-secret", &token), "wrong secret should fail");
    }

    #[test]
    fn token_format() {
        let token = make_token(b"s");
        let parts: Vec<&str> = token.splitn(2, '.').collect();
        assert_eq!(parts.len(), 2);
        assert_eq!(parts[0].len(), 64, "nonce hex should be 32 bytes = 64 hex chars");
        assert_eq!(parts[1].len(), 64, "HMAC hex should be 32 bytes = 64 hex chars");
    }
}
